sudo: false

language: cpp

cache:
  apt: true

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost-system1.54-dev
    - libboost-thread1.54-dev

compiler:
  - clang
  - gcc

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
